profile_1:
  required:
    - pseudocode
    - state
    - district
    - block
    - rural_urban
    - school_category
    - school_type
    - lowclass
    - highclass
    - managment
    - minority_school
  expected:
    - pseudocode
    - state
    - district
    - block
    - rural_urban
    - lgd_urban_local_body_name
    - lgd_ward_name
    - lgd_vill_name
    - lgd_vill_panchayat_name
    - lgd_block_name
    - school_category
    - school_type
    - lowclass
    - highclass
    - managment
    - pincode
    - special_school_for_cwsn
    - shift_school
    - resi_school
    - resi_type
    - minority_school
    - medium_instr1
    - medium_of_instr2
    - medium_of_instr3
    - medium_of_instr4
    - aff_board_sec
    - aff_board_hsec
    - approachable_road
    - pre_primary
    - anganwadi_yn
    - avg_instr_days
    - cce_yn
    - same_sch_b
    - same_sch_g
    - other_sch_b
    - other_sch_g
    - anganwadi_ecce_b
    - anganwadi_ecce_g

profile_2:
  required:
    - pseudocode
    - acad_inspections
    - smc_exists
    - grants_receipt
    - grants_expenditure
  expected:
    - pseudocode
    - balavatika_located_yn
    - special_training
    - material_training
    - free_text_books_pr
    - free_uniform_pr
    - free_text_books_up
    - free_uniform_up
    - acad_inspections
    - crc_coordinator
    - block_level_officers
    - district_officers
    - smc_exists
    - smc_smdc_same
    - smc_smdc_meetings
    - grants_receipt
    - grants_expenditure

facility:
  required:
    - pseudocode
    - total_class_rooms
    - total_boys_toilet
    - total_boys_func_toilet
    - total_girls_toilet
    - total_girls_func_toilet
    - electricity_availability
    - library_availability
    - internet
  expected:
    - pseudocode
    - building_status
    - no_building_blocks
    - pucca_building_blocks
    - boundary_wall
    - total_class_rooms
    - other_rooms
    - classrooms_in_good_condition
    - classrooms_needs_minor_repair
    - classrooms_needs_major_repair
    - separate_room_for_hm
    - total_boys_toilet
    - total_boys_func_toilet
    - total_girls_toilet
    - total_girls_func_toilet
    - total_boys_cwsn_toilet
    - func_boys_cwsn_friendly
    - total_girls_cwsn_toilet
    - func_girls_cwsn_friendly
    - urinal_boys
    - urinal_girls
    - handwash_near_toilet
    - hand_pump_yn
    - well_prot_yn
    - tap_yn
    - othsrc_yn
    - well_unprot_yn
    - pack_water_yn
    - hand_pump_fun_yn
    - well_prot_fun_yn
    - tap_fun_yn
    - othsrc_fun_yn
    - well_unprot_fun_yn
    - pack_water_fun_yn
    - rain_water_harvesting
    - handwash_facility_for_meal
    - electricity_availability
    - solar_panel
    - library_availability
    - book_bank
    - reading_corner
    - playground_available
    - playground_alt_yn
    - medical_checkups
    - availability_ramps
    - availability_of_handrails
    - furniture_availability
    - phy_lab_cond
    - chem_lab_cond
    - bio_lab_cond
    - math_lab_cond
    - lang_lab_cond
    - geo_lab_cond
    - home_sc_lab_cond
    - psycho_lab_cond
    - comp_lab_cond
    - comp_ict_lab_yn
    - ict_lab_yn
    - laptop
    - tablet
    - desktop
    - digiboard
    - teachdev_tot
    - server_tot
    - smart_class_tv_tot
    - projector
    - printer
    - internet
    - dth
    - spl_educator_yn

enrolment_1:
  required:
    - pseudocode
    - item_group
    - item_id
    - cpp_b
    - cpp_g
    - c1_b
    - c1_g
    - c12_b
    - c12_g
  expected:
    - pseudocode
    - item_group
    - item_id
    - cpp_b
    - cpp_g
    - c1_b
    - c1_g
    - c2_b
    - c2_g
    - c3_b
    - c3_g
    - c4_b
    - c4_g
    - c5_b
    - c5_g
    - c6_b
    - c6_g
    - c7_b
    - c7_g
    - c8_b
    - c8_g
    - c9_b
    - c9_g
    - c10_b
    - c10_g
    - c11_b
    - c11_g
    - c12_b
    - c12_g

enrolment_2:
  required:
    - pseudocode
    - item_group
    - item_id
    - cpp_b
    - cpp_g
    - c1_b
    - c1_g
    - c12_b
    - c12_g
  expected:
    - pseudocode
    - item_group
    - item_id
    - cpp_b
    - cpp_g
    - c1_b
    - c1_g
    - c2_b
    - c2_g
    - c3_b
    - c3_g
    - c4_b
    - c4_g
    - c5_b
    - c5_g
    - c6_b
    - c6_g
    - c7_b
    - c7_g
    - c8_b
    - c8_g
    - c9_b
    - c9_g
    - c10_b
    - c10_g
    - c11_b
    - c11_g
    - c12_b
    - c12_g

teacher:
  required:
    - pseudocode
    - total_tch
    - male
    - female
    - gen_tch
    - sc_tch
    - st_tch
    - obc_tch
  expected:
    - pseudocode
    - total_tch
    - male
    - female
    - transgender
    - gen_tch
    - sc_tch
    - st_tch
    - obc_tch
    - regular
    - contract
    - part_time
    - below_graduate
    - graduate
    - post_graduate_and_above
    - trained_comp
    - class_taught_pr
    - class_taught_upr
    - class_taught_pr_upr
    - class_taught_sec_only
    - class_taught_hsec_only
    - class_taught_upr_sec
    - class_taught_sec_hsec
    - class_taugt_pre_primary_only
    - class_taught_pr_and_pre_pri
    - teachers_involve_non_training_assignment
    - diploma_certificate
    - bachelor_of_ee
    - bed_equivalent
    - med_equivalent
    - other
    - none
    - diploma_special_edu
    - pursuing_rpc
    - diploma_ele_edu
    - early_childhood_tch
    - bed_nursery
    - trained_cwsn
